# Default values for WebServer_Helm

#Container settings
containers:
  name: k8s-app-web
  image: teranteks/test_task_python_webserver:v1
  ports: 5000

#Count of replicas
replicasCount: 2

#Service vars
svc_port: 5000
svc_target_port: 5000

#Namespace 
nm: app

#Horizontal scaling
autoscaling:
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 65
  averageValueMemory: 150Mi

