apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-horscaler-{{ .Release.Name }}
  namespace: {{ .Values.nm }}
  
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: deploy-app-{{ .Release.Name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.averageValueMemory }}

    
