apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-{{ .Release.Name }}
  namespace: {{ .Values.nm }}
  labels:
    app: k8s-deployment-app-{{ .Release.Name }} 

spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      project: k8s-app-{{ .Release.Name }}
  template:
    metadata:
      labels:
        project: k8s-app-{{ .Release.Name }}
    spec:
      containers:


        - name: {{ .Values.containers.name }}-{{ .Release.Name }}
          image: {{ .Values.containers.image }}
          ports:
            - containerPort: {{ .Values.containers.ports }}

          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.containers.ports }}

            initialDelaySeconds: 10
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 2


          readinessProbe:
            tcpSocket:
              port: {{ .Values.containers.ports }}  
            initialDelaySeconds: 5
            failureThreshold: 2
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 2

          startupProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.containers.ports }}
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 2

          resources:
             requests:
               memory: "50Mi"
               cpu: "250m"
             limits:
               memory: "260Mi"
               cpu: "500m" 
        


