apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-{{ .Release.Name }}
  namespace: {{ .Values.nm }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    env: dev
    owner: Teranteks
spec:
  defaultBackend:
    service:
      name: app-{{ .Release.Name }}-pod-service
      port:
        number: {{ .Values.svc_port }}
  rules:
  - host: pyapp.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: app-{{ .Release.Name }}-pod-service
              port:
                number: {{ .Values.svc_port }}

        - pathType: Prefix
          path: /healthcheck
          backend:
            service:
              name: app-{{ .Release.Name }}-pod-service
              port:
                number: {{ .Values.svc_port }}
    