
name: Docker_Img/Helm Repo Push 

on:
  branch_protection_rule:
    types: [created, edited, deleted]
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  build_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./app-code/Dockerfile
          tags: teranteks/test_task_python_webserver:v2
      
  helm_archive:

     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v3

      - name: Archive Helm Chart
        run: helm package ./WebServer_Helm ./